### DISCUSSION TITLE
Convert a CommaDelimitedList parameter into an array of Certificates

### DISCUSSION THREAD

**Discussion by HasanAouzoun** [aws-cloudformation/cfn-language-discussion#149] [Q&A]
Hi I am look to have a CommaDelimitedList parameter that contains a list of SSL certificate ARNs. Then use it in my ListenerCertificate resource. Something like this:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Parameters:
  SslCertificateList:
    Type: CommaDelimitedList
    Default: arn1,arn2,arn3,etc...

Resources:
ALBListenerHttpsCertificates:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties:
      Certificates: 
        'Fn::ForEach::CertificateList':
        - certArn
        - !Ref SslCertificateList
        - CertificateArn: !Ref certArn
      ListenerArn: !Ref ALBListenerHTTPS
``` 

However, I get this error in cloudformation:
"Transform AWS::LanguageExtensions failed with: Duplicate key 'CertificateArn' when merging keys to parent object in Fn::ForEach"

Is it possible to use the ForEach function to create a list of objects?
