### ISSUE TITLE
key/value pairs where value is null are wrongly removed

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-language-discussion#100]
### **Tell us about the bug**
the language extension transform will delete key/value pairs where the value is null.

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform:
- 'AWS::LanguageExtensions'
- 'AWS::Serverless-2016-10-31'

Resources:
  rLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      InlineCode: |
        def handler(event, context):
          print(event)
          return


  rTestMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition: 
        StartAt: myState
        States:
          myState:
            Type: Task
            Resource:  !GetAtt rLambda.Arn
            ResultPath: null
            End: true
      Policies:
      - Statement:
        - Sid: Test
          Effect: Allow
          Action:
          - lambda:Invoke*
          Resource: !GetAtt rLambda.Arn
```
will remove `ResultPath: null` which has value in [Step Functions](https://docs.aws.amazon.com/step-functions/latest/dg/input-output-resultpath.html)

If the Transform `AWS::LanguageExtensions` is not provided above everything works because SAM will transfer it to a string.  The problem is that its removed before SAM can correct it.

a more simple example:
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: 
- AWS::LanguageExtensions

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: null
```
while this template should be considered invalid.  The following transformed template will be transformed:
```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "Bucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {}
    }
  }
}
```

### **Expected behavior**

I expect `ResultPath: null` to be passed to SAM as needed

### **Observed behavior**

`ResultPath: null` is removed causing me step function issues

### **Test cases**
Please include a minimal CloudFormation template here that reproduces the issue

### **Additional context**
Anything else we should know?

https://github.com/aws-cloudformation/cfn-lint/issues/1657
https://github.com/aws/serverless-application-model/issues/1618

**Comment by jamesbting** [comment]
Thank you for bringing this to our attention! We will triage this issue and update it after investigations

**Comment by aidansteele** [comment]
+1 I'd like to see this fixed.

In the meantime, a workaround that was acceptable for us was to switch from using using an inline `Definition` to storing the definition in a separate file and using `DefinitionUri` and `DefinitionSubstitutions`. We'd prefer it inline, but this at least unblocked us.

**Comment by aka-raccoon** [comment]
This bug makes inline defined [AWS SAM connector](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/reference-sam-connector.html) unusable together with `AWS::LanguageExtensions`.

Eg:
```yaml
  MyFunc:
    Type: AWS::Serverless::Function
    Connectors:
      S3Conn:
        Properties:
          Destination:
            Id: Bucket
          Permissions:
          - Read
```

S3Conn is never created. If I remove `AWS::LanguageExtensions` and build/deploy a template, it works.
