### ISSUE TITLE
Fn::ToJsonString: Template error: every value of the context object of every Fn::Sub object must be a string or a function that returns a string

### ISSUE THREAD

**Issue by rix0rrr** [aws-cloudformation/cfn-language-discussion#103]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**

When `Fn::ToJsonString` is given an array retrieved from a resource using `{ Fn::GetAtt }`, the deployment fails with the following error:

```
Template error: every value of the context object of every Fn::Sub object must be a string or a function that returns a string
```

### **Expected behavior**

I want to see a JSON-ified representation of the array.

### **Observed behavior**

Deployment fails with an error.

### **Test cases**

```
Transform: AWS::LanguageExtensions
Resources:
  ZoneA5DE4B68:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: banana.com.
Outputs:
  Output:
    Value:
      Fn::ToJsonString:
        someList:
          Fn::GetAtt:
            - ZoneA5DE4B68
            - NameServers
```

### Additional context

I'm from the CDK team. It would make our life A LOT simpler if we could rely on CloudFormation built-ins to produce JSON strings from object literals (given that 99.9% of AWS APIs run on JSON 😅), but limitations of the `Fn::ToJsonString` functions make it unreliable, and therefore impossible for us to use (since the CDK middleware will not have the context that a human author would have on whether it's okay to use the function *in this particular use case* or not).

**Comment by benbridts** [comment]
This isn't called out in the documentation or RFX, but since the language extension is a transform / macro, it can't access Property Values from resources (or rather, only handles them opaquely). This happens because it has to run at change-set generation).

As an example, this does not output what you want, but is a valid way to use ToJsonString with GetAtt (!Join will convert the List to a String):

```yaml
Transform: AWS::LanguageExtensions
Resources:
  ZoneA5DE4B68:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: banana.com.
Outputs:
  Output:
    Value:
      Fn::ToJsonString:
        someString: !Join
          - ','
          - Fn::GetAtt:
              - ZoneA5DE4B68
              - NameServers

```

The output would be something like `{"someString":"ns-202.awsdns-25.com,ns-840.awsdns-41.net,ns-1768.awsdns-29.co.uk,ns-1281.awsdns-32.org"}`

**Comment by rix0rrr** [comment]
I know *why* this happening. I am reporting this as an uncovered need so you all can have an internal discussion on whether `{Fn::ToJsonString}` should be a proper intrinsic function or not.

**Comment by MalikAtalla-AWS** [comment]
Hey @rix0rrr, before I dive too deep into this issue, just want to double-check if the indentation issue in your example is accidental or intentional. I assume you mean this? (Output a sibling of Resources, not a child)
```yaml
Transform: AWS::LanguageExtensions
Resources:
  ZoneA5DE4B68:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: banana.com.
Outputs:
  Output:
    Value:
      Fn::ToJsonString:
        someList:
          Fn::GetAtt:
            - ZoneA5DE4B68
            - NameServers
```
