### ISSUE TITLE
Fn::ToJsonString: produces `null` when given an array

### ISSUE THREAD

**Issue by rix0rrr** [aws-cloudformation/cfn-language-discussion#104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**

When given an array, the output of the `Fn::ToJsonString` function is `null`, instead of `["a", "b", "c"]`.

### **Expected behavior**

A stringified version of the array

### **Observed behavior**

A useless value. Even an error would have been better.

### **Test cases**

```
Transform: AWS::LanguageExtensions
Outputs:
  Output:
    Value:
      Fn::ToJsonString:
        Fn::Split:
          - /
          - a/b/c
```

### **Additional context**

I'm from the CDK team. It would make our life A LOT simpler if we could rely on CloudFormation built-ins to produce JSON strings from object literals (given that 99.9% of AWS APIs run on JSON 😅), but limitations of the `Fn::ToJsonString` functions make it unreliable, and therefore impossible for us to use (since the CDK middleware will not have the context that a human author would have on whether it's okay to use the function *in this particular use case* or not).

**Comment by benbridts** [comment]
I can confirm this behavior, and it looks like this is a bug. The following snippet works in the way you'd expect:

```yaml
Transform: AWS::LanguageExtensions

Resources:
  Dummy:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  Output:
    Value:
      Fn::ToJsonString:
        ThisIsAList: !Split
          - /
          - a/b/c

```

**Comment by benbridts** [comment]
Sidenote:

> It would make our life A LOT simpler if we could rely on CloudFormation built-ins to produce JSON strings from object literals (given that 99.9% of AWS APIs run on JSON 😅),

I understand the sentiment, but we (as a consumers of Resource Types) should be advocating for better Resource Definitions, not "convert-to-json" workarounds.

To give a fictional example, a service requiring json as input should rework their provider to accept a typed data instead.

```
Resources:
  Bad:
    Type: AWS::Service::Resource
    Properties:
      Input: '{"a": "string that has to be valid json"}'
  Better:
    Type: AWS::Service::Resource
    Properties:
      Input:
        a: "mapping with undefined keys'
  Best:
    Type: AWS::Service::Resource
    Properties:
      Input:
        A: "mapping defined in the schema and following CFN conventions"
```
