### ISSUE TITLE
Support use of Fn::Split on values from parameters of type CommaDelimitedList.

### ISSUE THREAD

**Issue by rhbecker** [aws-cloudformation/cfn-language-discussion#106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**

Support use of [Fn::Split](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-split.html) on values from [parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#parameters-section-structure-properties) of type `CommaDelimitedList`.

### **Tell us about the problem you are trying to solve. What are you trying to do, and why is it hard?**

I have a comma delimited list of values (a list of users) that I want to parameterize. It seems appropriate to therefore use the `CommaDelimitedList` type. When I reference that parameter as the second argument for `Fn::Split`, I get an error ...

> Template error: every Fn::Split object requires two parameters, (1) a string delimiter and (2) a string to be split or a function that returns a string to be split.

Others have [reported the same issue](https://stackoverflow.com/a/54681624/2755803).

### **Are you currently working around this issue?**

I can use type `String` instead of `CommaDelimitedList`, but it seems like a shame to not use the more specific type.

### **What is the expect behavior with this new feature**

```YAML
Parameters:

  GroupMembers:
    Type: CommaDelimitedList

Resources:

    Group:
      Type: AWS::IAM::Group

    UserToGroup:
      Type: AWS::IAM::UserToGroupAddition
      Properties:
        GroupName: !Ref Group
        Users: !Split [',', !Ref GroupMembers]

```

### **Additional context**

n/a

### **Attachments**

n/a

**Comment by MalikAtalla-AWS** [comment]
You beat me to it @benbridts. Was just testing pretty much that example.
@rhbecker let us know if there is a bigger use case we're missing here.

**Comment by rhbecker** [comment]
Y'all are quick - I appreciate the responsiveness.

I ended up finding this info elsewhere, after posting this issue, along with some other related stuff I thought might be worth gathering here, as a reference for others who may struggle to intuit use of the `CommaDelimitedList` type, as I have.

**Feel free to close this issue**, unless you see something in the below that you think is improve-able, or worthy of mention in official docs. I don't have any specific suggestions in either regard, but can only say that I've found the `CommaDelimitedList` type to be less intuitive than would be ideal.

## conditions

Unlike with the `String` type, you can't simply test for equality against an empty value, like the below ...

```YAML
Parameters:

  GroupMembers:
    Type: CommaDelimitedList
    Default: ''

Conditions:

  IsNotEmpty: !Not [!Equals ['', !Ref GroupMembers]]
```

With the above approach, `Fn::Equals` will object with an error like ...

> Every Fn::Equals object requires a list of 2 string parameters

You can sidestep this by using `Fn::Join` to convert the param to a string, within the condition, to unblock the comparison ...

```YAML
Parameters:

  GroupMembers:
    Type: CommaDelimitedList
    Default: ''

Conditions:

  IsNotEmpty: !Not [!Equals ['', !Join ['', !Ref GroupMembers]]]
```

## nested stacks

When working with nested stacks (`Type: AWS::CloudFormation::Stack`), it doesn't seem to work to pass along a `CommaDelimitedList` parameter value from parent to child. In my example, both parent and child stacks define a `UserGroups` parameter, but a problem arises on the parent side when using the `CommaDelimitedList` type ...

```YAML
Parameters:

  UserGroups:
    Type: CommaDelimitedList
    Default: ''

Conditions:

  HasUserGroups: !Not [!Equals ['', !Join ['', !Ref UserGroups]]]

Resources:

    TestUser:
      Type: AWS::CloudFormation::Stack
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
      Properties:
        Parameters:
          UserGroups: !If [HasUserGroups, !Ref UserGroups, !Ref AWS::NoValue]
        [...]
```

With the above, my stack creation failed with an error ...

> Value of property Parameters must be an object with String (or simple type) properties

You can sidestep this by converting the parent's parameter to a `String` type (and adjusting the associated condition) - the child can continue specifying the receiving parameter as a `CommaDelimitedList` type.
