### ISSUE TITLE
Intrinsics in keys of a map (suggestion: Fn::KvFromMap, Fn::MapFromKv)

### ISSUE THREAD

**Issue by rix0rrr** [aws-cloudformation/cfn-language-discussion#107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**

Two functions to convert between two different representations of `(k, v)` pairs: `{ [key]: value, ... }` and `[ { key, value }, ... ]`.

```javascript
{
  "Fn::KvFromMap": {
    "KeyA": "ValueA",
    "KeyB": "ValueB"
  }
}

// -------------->

[
  { 
    "Key": "KeyA",
    "Value": "ValueA"
  },
  { 
    "Key": "KeyB",
    "Value": "ValueB"
  },
]
```

And

```javascript
{
  "Fn::MapFromKv": [
  { 
    "Key": "KeyA",
    "Value": "ValueA"
  },
  { 
    "Key": "KeyB",
    "Value": "ValueB"
  },
}

// -------------->

{
  "KeyA": "ValueA",
  "KeyB": "ValueB"
}
```

### **Tell us about the problem you are trying to solve. What are you trying to do, and why is it hard?**

We occasionally want to use CloudFormation intrinsics to produce a compound value from references. A common example is IAM Conditions where the keys need to contain a value that is constructed at deploy time:

```javascript
// A hypothetical bucket policy statement
{
  Effect: 'Allow',
  Action: 's3:GetObject',
  Resource: '*',
  Condition: {
    StringEquals: {
      'PrincipalTag:TrustedPrincipal': 'yes',
    },
  },
}

// A very real (and crazy-looking) IAM trust policy for an OIDC trust policy
// for EKS:
// (see https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html)
{
  Effect: "Allow",
  Principal: {
    Federated: "arn:aws:iam::11111111111:oidc-provider/someurl.amazonaws.com/oidc"
  },
  Action: "sts:AssumeRoleWithWebIdentity",
  Condition: {
    StringEquals: {
      "someurl.amazonaws.com/oidc:aud": "sts.amazonaws.com",
      "someurl.amazonaws.com/oidc:sub": "system:serviceaccount:MyNamespace:accountname"
    }
  }
}
```

In these examples:

* In `PrincipalTag:TrustedPrincipal`, `TrustedPrincipal` might come from a CloudFormation parameter.
* In `someurl.amazonaws.com/oidc:aud`, `someurl.amazonaws.com/oidc` is the `{ Fn::GetAtt }` output of a Custom Resource.

Both of these Policy statements **cannot be created in CloudFormation today**, because there is no way to use the required `{ Fn::Join }` or `{ Fn::Sub }` in a map key. With the proposed intrinsics, we would be able to write:

```yaml
Resources:
  SomeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-12
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal: 
              Federated: 
                Fn::Sub: 'arn:aws:iam:${AWS::AccountId}:oidc-provider/${Provider.IssuerUrl}'
            Condition:
              StringEquals:
                Fn::MapFromKv:
                  - Key: { Fn::Sub: '${Provider.IssuerUrl}:aud' }
                    Value: sts.amazonaws.com
                  - Key: { Fn::Sub: '${Provider.IssuerUrl}:sub' }
                    Value: { Fn::Sub: 'system:serviceaccount:${Namespace}:${ServiceAccount}' }
```

### **Are you currently working around this issue?**

Today we provision a Lambda into a customer's account to produce the correct JSON at runtime (https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.CfnJson.html) and customers aren't happy with it.

### **Additional context**

Personally, I find maps much more convenient to read than `Key/Value` pairs, and nearly all Tags implementations go by `Key/Value` pairs. It would also just be a nice way to write tags:

```yaml
Resources:
  SomeResource:
    Type: AWS::Some::Type
    Properties:
      Tags: 
        Fn::KvFromMap:
          TagA: ValueA
          TagB: ValueB
```
