### ISSUE TITLE
Fn::GetAtt not supported in AWS::Route53::RecordSet property HealthCheckId

### ISSUE THREAD

**Issue by shantgup** [aws-cloudformation/cfn-language-discussion#110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**

In the example template below, the Fn::GetAtt for AWS::Route53::RecordSet property HealthCheckId is not supported. We have confirmed this in the `eu-south-1` and `af-south-1` regions. 

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  myHealthCheck:
    Type: 'AWS::Route53::HealthCheck'
    Properties:
      HealthCheckConfig:
        Port: 80
        Type: HTTP
        ResourcePath: /example/index.html
        FullyQualifiedDomainName: [example.com](http://example.com/)
        RequestInterval: 30
        FailureThreshold: 3
      HealthCheckTags:
        - Key: SampleKey1
          Value: SampleValue1
        - Key: SampleKey2
          Value: SampleValue2
  myRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: [example.com](http://example.com/)
      HostedZoneId: Z03832112SJPMNXZJ61SG
      Type: 'CNAME'
      TTL: 900
      Type: A
      ResourceRecords:
      - 192.0.2.99
      HealthCheckId:
        'Fn::GetAtt':
          - myHealthCheck
          - HealthCheckId
```

### **Expected behavior**

Fn::GetAtt should be supported in AWS::Route53::RecordSet property HealthCheckId.

### **Observed behavior**

Fn::GetAtt is not supported in AWS::Route53::RecordSet property HealthCheckId.

### **Test cases**
Please include a minimal CloudFormation template here that reproduces the issue

Please use above template to reproduce the issue. 

### **Additional context**
Anything else we should know?

Creating this ticket on behalf of the customer, escalated by their account manager (TAM).
