### ISSUE TITLE
Intrinsic function for simplified IAM permissions

### ISSUE THREAD

**Issue by jlhood** [aws-cloudformation/cfn-language-discussion#111]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**

Wanted to get community feedback about the potential for adding an intrinsic function to simplify generation of minimal IAM policy permissions.

### **Tell us about the problem you are trying to solve. What are you trying to do, and why is it hard?**

Today when authoring declarative templates, writing minimal IAM permissions is difficult. For example, if I want to add minimal permissions allowing read/write data access to a specific DynamoDB table, I have to lookup [the DynamoDB IAM actions](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondynamodb.html) and determine which are associated with reading and writing data, add them to a policy document and then determine the right resource ARN to use for the DynamoDB table, either via manually constructing the ARN via `Fn::Sub` or if the table is defined in the template, using `Fn::GetAtt` to fetch the ARN.

CDK has a really nice solution for this: [grants](https://docs.aws.amazon.com/cdk/v2/guide/permissions.html#permissions_grants), but customers using declarative templates can't take advantage of this great feature.

### **Are you currently working around this issue?**
How are you currently solving this problem?

There are a few workarounds:

1. Follow the manual process described above, but it's time consuming and error-prone (easy to miss needed actions, e.g., for certain DDB write operations, `dynamodb:ConditionCheckItem` action is required, but this is an easy one to overlook).
1. Use [a managed policy](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/using-identity-based-policies.html#access-policy-examples-aws-managed) like `AmazonDynamoDBFullAccess`. Downside is this doesn't follow minimal permissions best practice (includes more actions than needed, uses `Resource: *`).
1. Migrate to CDK as it has a really slick solution for this: [grants](https://docs.aws.amazon.com/cdk/v2/guide/permissions.html#permissions_grants). Downside is migration can be costly or blocked on updating internal customer deployment tooling.

### **What is the expect behavior with this new feature**
Please include some code examples showing how this feature can be used.

Wondering about taking inspiration from CDK's grant methods and creating something like `Fn::Grant` that can be used by declarative template authors to create minimal permission sets for common use cases. Picturing something like this:

```yaml
Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      # ...

  Key:
    Type: AWS::KMS::Key
    Properties:
      # ...

  Role:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Fn::Grant
            - Table
            - ReadWriteData
          - Fn::Grant
            - Key
            - EncryptDecrypt
```

This would be equivalent to this:

```yaml
Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      # ...

  Key:
    Type: AWS::KMS::Key
    Properties:
      # ...

  Role:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
            - dynamodb:BatchGetItem
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:ConditionCheckItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
            Effect: Allow
            Resource:
            - !GetAtt Table.Arn
            - !Sub ${Table.Arn}/index/*
          - Action:
            - kms:Decrypt
            - kms:Encrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            Effect: Allow
            Resource: !GetAtt Key.Arn
```

Note, the above examples take the logical resource of a resource defined in the same template as the first argument, but this could potentially be enhanced to allow you to pass an arbitrary ARN value in as well.
