### ISSUE TITLE
LanguageExtension fails to execute condition

### ISSUE THREAD

**Issue by tayodok** [aws-cloudformation/cfn-language-discussion#113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**
What goes wrong? Please describe the issue in as much detail as possible.
When i add AWS::LanguageExtension Serverless-2016-10-31 to my CFN i get an error at build indicating a missing map in response to a FindInMap function. 
Which is true the map isn't there and should not be there. however the FindInMap should not be executed due to a condition placed on the resource. The CFN seems to execute all functions regardless.  

This doesn't happen without the LangEx. Builds normally then.

### **Expected behavior**
resource stack builds.

### **Observed behavior**
resource stack reports error of missing map.

### **Test cases**
Please include a minimal CloudFormation template here that reproduces the issue

### **Additional context**
Anything else we should know?

**Comment by arthurboghossian** [comment]
Thanks for bringing this to our attention @tayodok! Will discuss this behavior with our team and will get back to you

**Comment by tayodok** [comment]
Hi. I've figured out a solution that unblocks my issue. LangEx adds DefaultValue enhancement to FindInMap so providing this allows the mapping to execute.  i still question whether the behavior is optimal. going forward a default value will need to be provided for all uses of FindInMap to avoid executing null conditions.

**Comment by MalikAtalla-AWS** [comment]
The bugfix has rolled out to all regions and this issue is now resolved

**Comment by f0o** [comment]
Possibly related:

```
There was an error creating this change set
Transform AWS::LanguageExtensions failed with: Condition layout is incorrect
```

The Conditions:
```yaml
Conditions:

  # If you set the desired count of a service to be 0 or 1, then it means
  # that this service does not support auto scaling.
  ScalingSupported:
    Fn::Not:
      - Fn::Or:
          - !Equals [ !Ref DesiredCount, "0" ]
          - !Equals [ !Ref DesiredCount, "1" ]

  # Check if command exists
  CommandExist: !Not [ !Equals [!Ref Command, '']]

  # Check if secure environment variables are defined
  SecureEnv1Exist: !Not [ !Equals [!Ref SecureEnv1, '']]
  SecureEnv2Exist: !Not [ !Equals [!Ref SecureEnv2, '']]
  SecureEnv3Exist: !Not [ !Equals [!Ref SecureEnv3, '']]

  # Check if HTTP
  IsHTTP: !Equals [!Ref Protocol, 'http']

  # Check if None
  IsNone: !Equals [!Ref Protocol, 'none']

  # Check if service needs public access
  RequiresPublicAccess: !Equals [ !Ref AccessType, "Public" ]

  # Check if service needs internal access
  RequiresInternalAccess: !Equals [ !Ref AccessType, "Internal" ]

  # Check if this service requires an ALB
  # A service requires an ALB if it requires either public or internal access
  RequiresLoadBalancer: !Or
    - !Condition RequiresPublicAccess
    - !Condition RequiresInternalAccess

  # Check if service requires target group.
  # A service requires a target group only if:
  # - It needs public OR internal access
  RequiresTargetGroup: !Or
    - !Condition RequiresInternalAccess
    - !Condition RequiresPublicAccess

  PagerdutyIntegrationEnabled:
    Fn::Not: [ !Equals [ !Ref "PagerdutyIntegrationUrl", "disabled" ] ]

  # Check if sidecar init container is required
  RequiresSideCarInitContainer:
    Fn::Not: [ !Equals [ !Ref SSMSecrets, "" ] ]
```

Any idea?
