### ISSUE TITLE
Allow CommaDelimitedList stack parameters to be passed to CommaDelimitedList parameters in nested stacks.

### ISSUE THREAD

**Issue by josb** [aws-cloudformation/cfn-language-discussion#115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**
Allow `CommaDelimitedList` stack parameters to be passed to `CommaDelimitedList` parameters in nested stacks.

### **Tell us about the problem you are trying to solve. What are you trying to do, and why is it hard?**
I am trying to lower the cognitive burden of dealing with CloudFormation `CommaDelimitedList` parameters by making them adhere to the Principle Of Least Surprise more. Coming from other programming languages, it is surprising that one cannot pass a parameter of a given data type to a receiving parameter of the same data type.

### **Are you currently working around this issue?**
One has to define the parameter in the calling stack as a `String`.

### **What is the expect behavior with this new feature**
Main stack:
```
Parameters:
  Foo:
    Type: CommaDelimitedList
...
  S3Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "nested/stack.yaml"
      Parameters:
        Foo: !Ref Foo
```
Nested stack:
```
Parameters:
  Foo:
    Type: CommaDelimitedList

Resources:
  # Use !Ref Foo
```

### **Additional context**
Don't break existing behavior. But since this is currently prohibited this should not be a problem.
The current error one sees is:
```
Value of property Parameters must be an object with String (or simple type) properties
```

### **Attachments**
None.
