### ISSUE TITLE
Allow support for Fn::Equals to compare a string value to a list of strings value

### ISSUE THREAD

**Issue by eodeyemi14** [aws-cloudformation/cfn-language-discussion#117]
Community Note
Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

Tell us about your request
Allow `Fn::Equals` condition to support comparison of a string value to a list of strings values.

Tell us about the problem you are trying to solve. What are you trying to do, and why is it hard?
I am trying to create a condition statement which will compare a value and check if this value exists in a list. Currently, Fn::Equals only compares if two string values are equal. Adding this support will enable comparison of a value with different values in a list.

Are you currently working around this issue?
One has to create separate Fn::Equals condition statement for each of the values 

What is the expect behavior with this new feature
CFN stack:

```
Parameters:
Foos:
    Type: CommaDelimitedList

Conditions:
  CreateResources: !Not [!Equals [!Ref "AWS::AccountId", !Ref Foos]]

Resources:
  SNSTopic:
    Condition: CreateResources
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TestTopicName

```

The current error one sees with the above template is:

`Template error: every Fn::Equals object requires a list of 2 string parameters.`

Attachments
None.
