### ISSUE TITLE
Fn::LowerCase and Fn::UpperCaseFirst

### ISSUE THREAD

**Issue by adnweedon** [aws-cloudformation/cfn-language-discussion#122]

**Comment by MalikAtalla-AWS** [comment]
Hi @adnweedon, thanks for raising this feature request. Since this issue is related to the CloudFormation template language, I will transfer it to the cfn-language-discussion repo which was created for issues of this sort.

**Comment by benkehoe** [comment]
I'd prefer this being a single more general function, something like `Fn::StringTransform` that takes a string and an "enum" (another string, of course, but with a closed set of values) defining the transformation like `LowerCase`, etc.

**Comment by benbridts** [comment]
A note for when this would end up in an RFC: this function is not that useful when it can't access parameters (and/or resource properties). So it might not be a good fit for a transform

**Comment by benkehoe** [comment]
> might not be a good fit for a transform

This issue is not the right place for a discussion on this, but given the transform is the only place language evolution is happening at the moment, where would a request for a language feature that isn't appropriate for a transform implementation belong?

**Comment by benbridts** [comment]
I think this is the right place for the request, and I think following the RFC process would be great too.
But if the end result is in the language transform, I think this issue isn't solved. 

I'm not saying this shouldn't be done, I'm saying this should be done in a place that solves the stated problem

**Comment by rhbecker** [comment]
I'm trying to use the [StringFunctions](https://github.com/aws-cloudformation/aws-cloudformation-macros/tree/master/StringFunctions) macro within a `Fn::ForEach` loop, with the macro's `InputString` referencing the function's `Identifier`.

During changeset creation, I see an error ...

> Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: The value of parameter InputString under transform String must resolve to a string, number, boolean or a list of any of these.

Unless it's user error, I _think_ this relates back to the above conversation between the Bens, and _might_ provide a supporting reason for the preference stated by @benbridts - i.e. an implementation via the language extensions transform would seemingly behave in the same limited way I'm experiencing with the macro. Does that sound right to others?

✅  `Fn::ForEach` without macro

```YAML
Outputs:

  Fn::ForEach::Example:
    - Item
    - [ HELLO ]
    - Example${Item}:
        Export:
          Name: !Sub
            - ${AWS::StackName}:${lowercased}
            - lowercased: hello
        Value: x
```

✅  macro without `Fn::ForEach`

```YAML
Outputs:

  Example:
    Export:
      Name: !Sub
        - ${AWS::StackName}:${lowercased}
        - lowercased:
            Fn::Transform:
              Name: String
              Parameters:
                InputString: HELLO
                Operation: Lower
    Value: x
```

❌ both together

```YAML
Outputs:

  Fn::ForEach::Example:
    - Item
    - [ HELLO ]
    - Example${Item}:
        Export:
          Name: !Sub
            - ${AWS::StackName}:${lowercased}
            - lowercased:
                Fn::Transform:
                  Name: String
                  Parameters:
                    InputString: !Ref Item
                    Operation: Lower
        Value: x
```
