### ISSUE TITLE
Using !Ref in DeletionPolicy Breaks If Resource is Conditionally Created

### ISSUE THREAD

**Issue by nVlast** [aws-cloudformation/cfn-language-discussion#124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**
What goes wrong? Please describe the issue in as much detail as possible.

I am trying to create a CloudFormation stack where I use Parameters to set the DeletionPolicy on a resource that's created conditionally (via a Condition controlled by a different Parameter - see "Test cases" below). The creation fails, saying that I'm using an unsupported expression for DeletionPolicy.

### **Expected behavior**

The stack should have been created successfully.

### **Observed behavior**

Stack creation fails with:
```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::LanguageExtensions failed with: Unsupported expression for DeletionPolicy in resource Bucket2
```

### **Test cases**
Please include a minimal CloudFormation template here that reproduces the issue

```yaml
Transform: AWS::LanguageExtensions

Parameters:
  DeletionPolicy:
    Type: String
    Default: Delete

  CreateBucket2:
    Type: String
    AllowedValues:
      - "false"
      - "true"
    Default: "false"

Conditions:
  ShouldCreateBucket2: !Not [!Equals [!Ref CreateBucket2, "false"]]

Resources:
  Bucket1:
    DeletionPolicy: !Ref DeletionPolicy
    Type: AWS::S3::Bucket

  Bucket2:
    Condition: ShouldCreateBucket2
    DeletionPolicy: !Ref DeletionPolicy
    Type: AWS::S3::Bucket
```

### **Additional context**
Anything else we should know?

We use this approach with a template that deploys Aurora databases and it seemed to work fine up until yesterday (24/4/2023).

**Comment by renerask** [comment]
I started having issues with the LanguageExtensions transform today (first deployment in days).

Templates that include the LanguageExtensions transform but do not use it for anything started breaking when creating a CloudFormation changeset.  CloudFormation is stuck in a `REVIEW_IN_PROGRESS` even though the Change Set has a `FAILED`  status. and the the exits with this error message:

`Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::LanguageExtensions failed with: Error parsing the template`

I have one template which actually uses the the transform which also breaks with the same errors as above.
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::LanguageExtensions
Parameters:
  EnvType:
    Description: Type of environment
    Type: String

Conditions:
  IsDevEnvironment: !Equals [ !Ref EnvType, 'dev' ]

Resources:
  FsxShareFS:
    Type: AWS::FSx::FileSystem
    DeletionPolicy: !If [ IsDevEnvironment, 'Delete', 'Retain' ]
```

Looks like a bad software rollout as AWS.
