### ISSUE TITLE
Transform AWS::LanguageExtensions failed with: Fn::If layout is incorrect

### ISSUE THREAD

**Issue by miguel-aws** [aws-cloudformation/cfn-language-discussion#135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**

Trying to use [Fn::If](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-if) within [Fn::ForEach](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-foreach.html) to reference a [condition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-if) but CloudFormation returns `Transform AWS::LanguageExtensions failed with: Fn::If layout is incorrect`

Docs state that [Fn::If is supported within Fn::ForEach](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-foreach.html#intrinsic-function-reference-foreach-nested-functions).

See **Test cases** section for scenarios and replication template.

### **Expected behavior**

Template validates correctly, the conditions are recognized, and proceeds to create the resources.

### **Observed behavior**

Stack events report `Transform AWS::LanguageExtensions failed with: Fn::If layout is incorrect`

### **Test cases**

Referencing `${Identifier}` variable with !Sub to form the condition name causes the error.

            !If
              - !Sub "${ServerType}CreateSecondaryVolume"
              - - DeviceName: xvdf
                  Ebs:
                    DeleteOnTermination: true
                    Encrypted: true
                    VolumeSize: 100
                    VolumeType: gp3
                    Iops: 3000
              - !Ref AWS::NoValue

If we hardcode the condition name (i.e. BackupCreateSecondaryVolume), the stack goes through with no problems,

            !If
              - BackupCreateSecondaryVolume
              - - DeviceName: xvdf
                  Ebs:
                    DeleteOnTermination: true
                    Encrypted: true
                    VolumeSize: 100
                    VolumeType: gp3
                    Iops: 3000
              - !Ref AWS::NoValue

**Template**

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Mappings:
  ServerTypeMapping:
    Backup:
      CreateSecondaryVolume: true
    SQL:
      CreateSecondaryVolume: false
Conditions:
  BackupCreateSecondaryVolume: !Equals [!FindInMap [ServerTypeMapping, Backup, CreateSecondaryVolume], true]
  SQLCreateSecondaryVolume: !Equals [!FindInMap [ServerTypeMapping, SQL, CreateSecondaryVolume], true]
Resources:
  'Fn::ForEach::ServerTypes':
  - ServerType
  - [Backup, SQL]
  - LaunchTemplate${ServerType}:
      Type: AWS::EC2::LaunchTemplate
      Properties:
        LaunchTemplateData:
          BlockDeviceMappings:
            !If
              - !Sub "${ServerType}CreateSecondaryVolume"
              - - DeviceName: xvdf
                  Ebs:
                    DeleteOnTermination: true
                    Encrypted: true
                    VolumeSize: 100
                    VolumeType: gp3
                    Iops: 3000
              - !Ref AWS::NoValue
        LaunchTemplateName:
          Fn::Join: ["-", [!Sub "${AWS::StackName}", !Sub "${ServerType}"]]
```

**Comment by arthurboghossian** [comment]
@mparana CloudFormation currently doesn't support an intrinsic function for the 1st parameter (the condition name) of the Fn::If intrinsic function.

For example, calling CreateStack on the template below would result in CreateStack failing with `Template error: Fn::If requires a list argument with the first element being a condition`:

```
AWSTemplateFormatVersion: 2010-09-09
Conditions:
  Cond:
    !Equals ["0", "1"]
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !If
        - !Sub 'Cond'
        - TrueTopic
        - FalseTopic
```

So allowing intrinsic functions for the condition name would be a new feature, which would be part of the `AWS::LanguageExtensions` Transform.

If possible, can you please create a feature request GitHub issue within this repo?
