### ISSUE TITLE
Intrinsic functions for the condition name in Fn::If

### ISSUE THREAD

**Issue by miguel-aws** [aws-cloudformation/cfn-language-discussion#137]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**

Re: [Transform AWS::LanguageExtensions failed with: Fn::If layout is incorrect #135](https://github.com/aws-cloudformation/cfn-language-discussion/issues/135#issue-1837316522) 

We would like to request support for intrinsic functions for the condition name.

### **Tell us about the problem you are trying to solve. What are you trying to do, and why is it hard?**

Trying to use [Fn::If](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-if) within [Fn::ForEach](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-foreach.html) to reference a [condition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-if) but CloudFormation returns `Transform AWS::LanguageExtensions failed with: Fn::If layout is incorrect`

Docs state that [Fn::If is supported within Fn::ForEach](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-foreach.html#intrinsic-function-reference-foreach-nested-functions).

### **Are you currently working around this issue?**

Hardcoding condition name.

### **What is the expected behavior with this new feature**
Example template of ideal use case:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Mappings:
  ServerTypeMapping:
    Backup:
      CreateSecondaryVolume: true
    SQL:
      CreateSecondaryVolume: false
Conditions:
  BackupCreateSecondaryVolume: !Equals [!FindInMap [ServerTypeMapping, Backup, CreateSecondaryVolume], true]
  SQLCreateSecondaryVolume: !Equals [!FindInMap [ServerTypeMapping, SQL, CreateSecondaryVolume], true]
Resources:
  'Fn::ForEach::ServerTypes':
  - ServerType
  - [Backup, SQL]
  - LaunchTemplate${ServerType}:
      Type: AWS::EC2::LaunchTemplate
      Properties:
        LaunchTemplateData:
          BlockDeviceMappings:
            !If
              - !Sub "${ServerType}CreateSecondaryVolume"
              - - DeviceName: xvdf
                  Ebs:
                    DeleteOnTermination: true
                    Encrypted: true
                    VolumeSize: 100
                    VolumeType: gp3
                    Iops: 3000
              - !Ref AWS::NoValue
        LaunchTemplateName:
          Fn::Join: ["-", [!Sub "${AWS::StackName}", !Sub "${ServerType}"]]
```

**Comment by skinsman** [comment]
I've hit this problem too and the AWS Support Engineer has just pointed me here.  They are investigating further.
BTW I've tried some variations of syntax including replacing !Sub with !Join, with no luck.

**Comment by rshayman** [comment]
I've encountered the same issue.  Surprised they have not fixed this over the last 2 months.  Seems like an oversight on their part.  The fact that the transformation is generating an error means it is looking at the yaml and just doesn't like what it sees.  Surely this should be fairly simple to fix.

**Comment by jeffsays** [comment]
Bump.

Any movement on this in the past 2 years?  This seems like a missing part of the functionality.

If I can create a condition with the Fn::Equals using a Fn::Sub statement

```yaml
Conditions:
  'Fn::ForEach::CheckTrue':
    - Identifier
    - Ref: MyList
    - '${Identifier}Dashboard': !Equals
        - 'Fn::Sub': '${Identifier}'
        - Ref: MyParameter
```

And then Conditionally generate resources with that condition:

```yaml
Resources:
  'Fn::ForEach::PossibleDashboard':
    - Identifier
    - Ref: MyList
    - '${Identifier}Configuration':
        Type: Custom::Configuration
        Condition: !Sub '${Identifier}Dashboard'
```

I should be able to generate outputs and use the condition:

```yaml
Outputs:
  'Fn::ForEach::CheckTrueOutput':
    - Identifier
    - Ref: MyList
    - "${Identifier}Dashboard":
        Value: !If
          - 'Fn::Sub': '${Identifier}Dashboard'
          - "true"
          - "false"
```

I am aware that I could have a _conditional_ output that only exists if the condition is true, but there are cases where someone may want to explicitly see true/false, and not simply see true when true:

```yaml
Outputs
  'Fn::ForEach::CheckTrueOutput':
    - Identifier
    - Ref: MyList
    - "${Identifier}Dashboard":
        Value: "true"
        Condition: !Sub '${Identifier}Dashboard'
```
