### ISSUE TITLE
Function to find all Resources of a specific type (to use with Fn::ForEach)

### ISSUE THREAD

**Issue by cortexcompiler** [aws-cloudformation/cfn-language-discussion#138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**
An intrinsic function that can find all resources of a specific type. A bonus would be an ability to filter them based upon a Logical Id pattern or even other properties.

### **Tell us about the problem you are trying to solve. What are you trying to do, and why is it hard?**
**Example use case:**
I would like to add an `AWS::Logs::SubscriptionFilter` for every `AWS::Logs::LogGroup` defined in my template.  Every property is the same for the SubscriptionFilter except for the Logical Id, and the `LogGroupName`.  This seems like a great use case for `Fn::ForEach`, if I could just get the list of Logical Ids for the LogGroups.  One other note: the LogGroups may have some variability so I cannot drive their creation using a list or map (and so do not have that to drive the creation of the `SubscriptionFilter` resources).  I have been unable to find a satisfactory solution in CloudFormation examples or documentation.

Without this I end up having to maintain and copy/paste a lot of boilerplate configuration and run the risk of missing a `SubscriptionFilter` for a `LogGroup`.

### **Are you currently working around this issue?**
I am currently copying and pasting the same `AWS::Logs::SubscriptionFilter` block and then changing the resource id and `LogGroupName`.

### **What is the expected behavior with this new feature**
Rather than having to do something like this (simplified example)
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::LanguageExtensions
- AWS::Serverless-2016-10-31
Description: Example to demonstrate need

Globals:
  Function:
    Runtime: nodejs16.x

Resources:
  FirstFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      MemorySize: 128
      CodeUri: .
      Handler: index.handler

  FirstFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FirstFunction}"

  FirstFunctionLogSubscriptionFilter: 
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:common-log-ingestion
      FilterPattern: ''
      LogGroupName: !Ref FirstFunctionLogGroup

  SecondFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      MemorySize: 256
      CodeUri: .
      Handler: index.handler

  SecondFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SecondFunction}"

  SecondFunctionLogSubscriptionFilter: 
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:common-log-ingestion
      FilterPattern: ''
      LogGroupName: !Ref SecondFunctionLogGroup

```

I am envisioning something like this (in this case I am driving both the `LogGroup` and the `SubscriptionFilter` off of the `Function` resources):
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::LanguageExtensions
- AWS::Serverless-2016-10-31
Description: Example to demonstrate need

Globals:
  Function:
    Runtime: nodejs16.x

Resources:
  FirstFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      MemorySize: 128
      CodeUri: .
      Handler: index.handler

  SecondFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      MemorySize: 256
      CodeUri: .
      Handler: index.handler

  # Iterate over each AWS::Serverless::Function (bonus: Logical Id matching pattern "^.*Function")
  # and for each Function create a LogGroup and SubscriptionFilter for that group
  Fn::ForEach::FunctionLogGroups:
    - FunctionLogicalId
    - Fn::FindResources: 
        Type: AWS::Serverless::Function
        Pattern: ^.*Function
    - "${FunctionLogicalId}LogGroup": 
        Type: AWS::Logs::LogGroup
        Properties:
          LogGroupName: !Sub "/aws/lambda/${FunctionLogicalId}"

      "${FunctionLogicalId}SubscriptionFilter": 
        Type: AWS::Logs::SubscriptionFilter
        Properties:
          DestinationArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:common-log-ingestion
          FilterPattern: ''
          LogGroupName: !Ref ${FunctionLogicalId}LogGroup
```

### **Additional context**
This could save time and prevent issues caused by copy/paste errors and omissions.
