### ISSUE TITLE
AWS::LanguageExtensions not supporting RetainExceptOnCreate

### ISSUE THREAD

**Issue by ZalmnS** [aws-cloudformation/cfn-language-discussion#139]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**
Recently, CloudFormation released support for RetainExceptOnCreate as a new value for the DeletionPolicy Attribute.
https://aws.amazon.com/about-aws/whats-new/2023/07/aws-cloudformation-deletion-policies-dev-test-cycle/

When attempting to use the AWS::LanguageExtensions within the Template below including the "RetainExceptOnCreate" Value for the DeletionPolicy Attribute, you encounter the following error:
Template:
```
Transform: 'AWS::LanguageExtensions'
Resources:
  S3:
    DeletionPolicy: RetainExceptOnCreate
    Type: AWS::S3::Bucket
```

Error:
```
Transform AWS::LanguageExtensions failed with: Unrecognized DeletionPolicy RetainExceptOnCreate for resource S3. Rollback requested by user.
```

### **Expected behavior**
The expected behavior is that the AWS::LanguageExtensions Transform would be able to interpret RetainExceptOnCreate as a valid string to be used within the DeletionPolicy Attribute.

I suspect that there is a list of strings anticipated for the DeletionPolicy Attribute, and "RetainExceptOnCreate" needs to be added into the list of strings

### **Observed behavior**
Currently the Language Extension throws the error below:

Transform AWS::LanguageExtensions failed with: Unrecognized DeletionPolicy RetainExceptOnCreate for resource S3. Rollback requested by user.

### **Test cases**
Please include a minimal CloudFormation template here that reproduces the issue

```
Transform: 'AWS::LanguageExtensions'
Resources:
  S3:
    DeletionPolicy: RetainExceptOnCreate
    Type: AWS::S3::Bucket
```

You'll be met with the error right away within the Stack Events.

### **Additional context**
Anything else we should know?
N/A
