### ISSUE TITLE
Feature Request: Fn::Lower and Fn::Upper Intrinsic functions

### ISSUE THREAD

**Issue by arthurboghossian** [aws-cloudformation/cfn-language-discussion#142]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**
What do you want us to build?

1. New intrinsic function `Fn::Lower` that would take in a String and return the String with all letters converted to lowercase
2. New intrinsic function `Fn::Upper` that would take in a String and return the String with all letters converted to uppercase

### **Tell us about the problem you are trying to solve. What are you trying to do, and why is it hard?**

Instead of having to create another parameter with the lowercase and/or uppercase version of a parameter, the `Fn::Lower` and/or `Fn::Upper` intrinsic functions can be used.

Example template with desired behavior:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Stage:
    Type: String
    Default: Prod
    AllowedValues:
      - Prod
      - Gamma
      - Beta
Resources:
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Sub 'My${Stage}Topic'
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 
        - 'my-bucket-${StageLower}-my-website.com'
        - StageLower:
            'Fn::Lower': !Ref Stage
```

This is what the template has to look like now, where another Parameter has to be provided, and would have to be used in the right context:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Stage:
    Type: String
    Default: Prod
    AllowedValues:
      - Prod
      - Gamma
      - Beta
  StageLower:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - gamma
      - beta
Resources:
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Sub 'My${Stage}Topic'
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 
        - 'my-bucket-${StageLower}-my-website.com'
        - StageLower: !Ref StageLower
```

### **Are you currently working around this issue?**
Defining another parameter that is the same value of the parameter, but with lowercase/uppercase characters.

### **What is the expected behavior with this new feature**
The intrinsic function(s) `Fn::Lower` and `Fn::Upper` can be used to return the lowercase/uppercase version of the specified String.
