### ISSUE TITLE
${Identifier.number}  in Fn::ForEach to get processing number

### ISSUE THREAD

**Issue by shiosalt** [aws-cloudformation/cfn-language-discussion#145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**
To summarize, I would like to get what processing number is currently on.
As an example, I want to create subnets and other resources for each AZ to support a redundant environment.
But I cannot create OutputKey with an AWS-specific parameter type,like this.
sample template 1
```
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'
Parameters:
  paramAZs:
    Type: List<AWS::EC2::AvailabilityZone::Name>
  paramVpc:
    Type: AWS::EC2::VPC::Id
Mappings:
  mapSubnetIP:
    ap-northeast-1a:
      Subnet: 192.168.110.0/24
    ap-northeast-1c:
      Subnet: 192.168.111.0/24
    ap-northeast-1d:
      Subnet: 192.168.112.0/24
Resources:
  'Fn::ForEach::AZs':
  - myAZ
  - !Ref paramAZs
  - 'PrivateSubnet${myAZ}':
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref paramVpc
        CidrBlock: !FindInMap 
          - mapSubnetIP
          - !Ref myAZ
          - Subnet
```
This sample template will fail with this error message.
`Transform AWS::LanguageExtensions failed with: OutputKey 'PrivateSubnetap-northeast-1a' should be alphanumeric.`

${Identifier.number} can solve this issue, and it will be simple.
sample template 2.
```
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'
Parameters:
  paramAZs:
    Type: List<AWS::EC2::AvailabilityZone::Name>
  paramVpc:
    Type: AWS::EC2::VPC::Id
Resources:
  Fn::ForEach::AZs:
  - myAZ
  - !Ref paramAZs
  - 'PrivateSubnet${myAZ.number}':
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref paramVpc
        CidrBlock: !Select
          - !Sub ${myAZ.number} 
          - ["192.168.110.0/24", "192.168.111.0/24","192.168.112.0/24"]
```

### **Are you currently working around this issue?**
Defining each resource separately without using ForEach.

### **What is the expected behavior with this new feature**

In sample template 2 ,${myAZ.number} will be replaced 0,1,2 .. depend on ForEach's list.
It is simple, so no work for replacing - , _ or others for KeyName.

And, also I use ${myAZ.number} for selecting subnet from list.
I don't need to know what is ${myAZ} value (ex. ap-northeast-1a), and I can reduce Mappings section.

### **Additional context**
1. Almost all the resource IDs use "-", and We cannot use "-" in Keyname. We can't use resource IDs in Fn::ForEach's list now.
2. All the AWS-specific parameter types use "-". so now We can't use them in Fn::ForEach ,too.
3. I think this can be done without much regard to the order of text transformation, so this New feature will suit  for Cfn's transform,
 and it might not need so hardwork.
4. Minitour has also reported almost the same issue in  #140  .

### **Attachments**
no attachment

**Comment by benbridts** [comment]
Another way to do this, would be to only ask for the (last) letter of the AZ as input:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'
Parameters:
  paramAZs:
    Type: CommaDelimitedList
    Default: a,c,d
  paramVpc:
    Type: AWS::EC2::VPC::Id
Mappings:
  mapSubnetIP:
    ap-northeast-1a:
      Subnet: 192.168.110.0/24
    ap-northeast-1c:
      Subnet: 192.168.111.0/24
    ap-northeast-1d:
      Subnet: 192.168.112.0/24
Resources:
  'Fn::ForEach::AZs':
  - myAZ
  - !Ref paramAZs
  - 'PrivateSubnet${myAZ}':
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref paramVpc
        CidrBlock: !FindInMap 
          - mapSubnetIP
          - !Sub "${AWS::Region}${myAZ}"
          - Subnet
```

**Comment by shiosalt** [comment]
Thank you for your comment, benbridts.
It is a nice idea for replacing sample 1.
However, I would like the template to work dynamically and not just in some regions.
For example, sample 1 will not work for a StackSet with multiple regions, but sample 2 will work.

**Comment by benbridts** [comment]
> For example, sample 1 will not work for a StackSet with multiple regions, but sample 2 will work

You can leave out the region-specific mapping, if that is what you'd need. That way you also don't have to worry as much about how you're going to override the `paramAZs` parameter for each region (because in sample 2 they will have to be different for every region).

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'
Parameters:
  paramAZs:
    Type: CommaDelimitedList
    Default: a,c,d
  paramVpc:
    Type: AWS::EC2::VPC::Id
Mappings:
  mapSubnetIP:
    a:
      Subnet: 192.168.110.0/24
    c:
      Subnet: 192.168.111.0/24
    d:
      Subnet: 192.168.112.0/24
Resources:
  'Fn::ForEach::AZs':
  - myAZ
  - !Ref paramAZs
  - 'PrivateSubnet${myAZ}':
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref paramVpc
        CidrBlock: !FindInMap 
          - mapSubnetIP
          - !Ref myAZ
          - Subnet
```
