### ISSUE TITLE
False change being introduced when using Fn::ToJsonString

### ISSUE THREAD

**Issue by mrlikl** [aws-cloudformation/cfn-language-discussion#150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**
What goes wrong? Please describe the issue in as much detail as possible.

After the macro processing for Fn::ToJsonString the results are not idempotent. Every time the macro is processed, a new hash is generated for the Fn Sub's in place of Ref's. For example 
```
 "StringLike": {
                  "aws:SourceArn": {"Ref": "SNSReportTopic"}
                }
```
will be converted to 

```
{\"aws:SourceArn\":\"${7eb8259df4484292967e4918a3ee0b3d}\"}}}]}",
        {
          "7eb8259df4484292967e4918a3ee0b3d": {
            "Ref": "SNSReportTopic"
          }
```

the next time it will change 

```
{\"aws:SourceArn\":\"${bb44733c1907414696ec158d5ad1805f}\"}}}]}",
        {
          "bb44733c1907414696ec158d5ad1805f": {
            "Ref": "SNSReportTopic"
          }
```

This is introducing a false change while creating create-changeset. Even though executing this change set will not update the resource (as there are no change in values as such hence CFN will not update). 

### **Expected behavior**

The hash remains after every run.

### **Observed behavior**

The hash changes after every run.

### **Test cases**
Please include a minimal CloudFormation template here that reproduces the issue

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::LanguageExtensions
Resources:
  SNSReportTopic:
    Type: AWS::SNS::Topic
    Properties: {}
  MyResourcePolicy:
    Type: "AWS::XRay::ResourcePolicy"
    Properties:
      BypassPolicyLockoutCheck: "false"
      PolicyDocument:
        "Fn::ToJsonString":
          Version: "2012-10-17"
          Statement:
            - Sid: SNSAccess
              Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action:
                - "xray:PutTraceSegments"
                - "xray:GetSamplingRules"
                - "xray:GetSamplingTargets"
              Resource: "*"
              Condition:
                StringEquals:
                  "aws:SourceAccount": !Ref "AWS::AccountId"
                StringLike:
                  "aws:SourceArn": !Ref SNSReportTopic
      PolicyName: MySnsActiveTracingPolicy
```

### **Additional context**
Anything else we should know?
