### ISSUE TITLE
Combination of ForEach, !Sub and AWS::StackName will cause stack creation to fail

### ISSUE THREAD

**Issue by kallu** [aws-cloudformation/cfn-language-discussion#151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**

Using `AWS::StackName` pseudo parameter with ForEach loop variable in `!Sub` will cause stack creation to fail.

### **Expected behavior**

`!Sub` should work within ForEach -loops as normal, including pseudo parameters like `AWS::StackName`

### **Observed behavior**

Stack creation will fail with error

`Template format error: Unresolved resource dependencies [X] in the Resources block of the template`

### **Test cases**

This template fails

```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 2 VPCs using ForEach
Transform: 'AWS::LanguageExtensions'

Resources:

  'Fn::ForEach::Network':
  - X
  - [ A, B ]
  - VPC${X}:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        Tags:
          - Key: Name
            Value: !Sub '${AWS::StackName} VPC ${X}'
```

Similar template, using `Join` instead of `Sub` works. You can also change ``AWS::StackName`` to `AWS::Region` and it will work. So far I have found only the combination of `!Sub`, `AWS::StackName` and loop variable failing like this.

```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 2 VPCs using ForEach
Transform: 'AWS::LanguageExtensions'

Resources:

  'Fn::ForEach::Network':
  - X
  - [ A, B ]
  - VPC${X}:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        Tags:
          - Key: Name
            Value: !Join
              - ' '
              - - !Ref AWS::StackName
                - 'VPC'
                - !Ref X
```
