### ISSUE TITLE
ChangeSet creation failure with {{IntrinsicFunction:(stack_name)//Fn::ImportValue}} is not allowed.

### ISSUE THREAD

**Issue by mrlikl** [aws-cloudformation/cfn-language-discussion#152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**
What goes wrong? Please describe the issue in as much detail as possible.

When a nested stack is referencing a parameter that is passed from the root/parent stack as intrinsic functions, a similar error 
`Usage of {{IntrinsicFunction:stack_name//Fn::ImportValue}} is not allowed.`
`Usage of {{IntrinsicFunction:stack_name/logical_idFn::GetAtt}} is not allowed.`
is occurring

### **Expected behavior**

Change set to be successfully create

### **Observed behavior**

Change set failure with the error

### **Test cases**
Please include a minimal CloudFormation template here that reproduces the issue

Create a stack with simple S3 bucket 

root.yml
```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RootS3Bucket:
    Type: AWS::S3::Bucket
```

Create change set with a nested stack like below - 

root.yml
```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TestRule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested.yml
      Parameters:
        TagValue: !GetAtt RootS3Bucket.Arn
  RootS3Bucket:
    Type: AWS::S3::Bucket
```

nested.yml
```
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'

Parameters:
  TagValue:
    Type: String

Resources:
  'Fn::ForEach::Buckets':
    - Names
    - - Store1
      - Store2
    - '${Names}Bucket':
        Type: 'AWS::S3::Bucket'
        Properties:
          Tags:
            - Key: parameters
              Value: !Ref TagValue
```

### **Additional context**
Anything else we should know?
