### ISSUE TITLE
AWS::Serverless::Api forcing "Stage" stage

### ISSUE THREAD

**Issue by marcus233** [aws-cloudformation/cfn-language-discussion#155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**

AWS::Serverless::Api is forcing the creation of a stage named "Stage".  I have a deployed and working serverless API  with the stage "dev" and no other stages. I recently tried to update one of the lambdas for my API and redeploy the sam/cfn template and got the error `Resource handler returned message: "Stage Stage on RestApi 267ovg0dqb was not found (Service: ApiGateway, Status Code: 404, Request ID: 4e03d485-ed1b-4e32-8ffe-275a1b5fb743)" (RequestToken: b5e3b094-81a9-3ca8-a719-cd7360f157aa, HandlerErrorCode: NotFound)`.
I came across this bug report: https://github.com/aws/serverless-application-model/issues/3548 and tried the suggested fix and still got the error. 
Troubleshooting I removed the API Gateway by commenting it out of my template, then recreating it by uncommenting the same block. After a deploy I get an API Gateway with 2 stages: dev and Stage. My last successful deploy was 11/15/2023 so this is a fairly recent change in behavior.

### **Expected behavior**
Create only the stage defined.

### **Observed behavior**
Unwanted creation of "Stage" stage
![1Z9E44Sv](https://github.com/aws-cloudformation/cfn-language-discussion/assets/3539481/6e742a66-2365-45db-8bab-778253760228)

### **Test cases**
```
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev   # Note here I've removed a !Ref Stage seen in serverless-application-model#3548
      MethodSettings:
        - LoggingLevel: INFO
          MetricsEnabled: True
          ResourcePath: "/*"  
          HttpMethod: "*"  

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: api.lambda_handler
      Events:
        MyFirstApi:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /myapi
            Method: POST
```
