### ISSUE TITLE
AWS::LanguageExtensions transform breaks with ContainerDependency blocks ECS

### ISSUE THREAD

**Issue by daghaian** [aws-cloudformation/cfn-language-discussion#160]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**
What goes wrong? Please describe the issue in as much detail as possible.

This issue was encountered when we tried to take advantage of the `ForEach` intrinsic function provided by LanguageExtensions.

When adding the `Transform: AWS::LanguageExtensions` block to the top of our previously working stack, any attempts to deploy the stack fail with the error:

`Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Fragment returned by transform AWS::LanguageExtensions is null`

After drilling down into our stack to identify the offending resource, it was found that its specifically the `DependsOn` container dependency we have defined for our ECS task definition.

To be clear, no additional changes were made to the stack other than the addition of the transform line at the top of the stack.

```yaml
 -  Name:  test-container
    Image:  nginx
    DependsOn:
      - Condition: COMPLETE
        ContainerName: dependent-container
    MountPoints:
      - ContainerPath: /configs
        SourceVolume: configs
    FirelensConfiguration:
      Type: fluentbit
      Options:
        enable-ecs-log-metadata: "true"
        config-file-type: "file"
        config-file-value: "/configs/parse-json.conf"
    MemoryReservation: 50
```

### **Expected behavior**

It would be expected that a previously working stack would still be deployable with the inclusion of the LanguageExtensions

### **Observed behavior**

Failure is encountered as mentioned above. Removing **only** the `DependsOn` container dependency block resolves the issue but this is not a feasible resolution.

### **Test cases**
Please include a minimal CloudFormation template here that reproduces the issue

### **Additional context**
Anything else we should know?
