### ISSUE TITLE
Fn::ForEach Issue - Unable to reference resources with logical IDs generated using the &{} syntax

### ISSUE THREAD

**Issue by miguel-aws** [aws-cloudformation/cfn-language-discussion#162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about the bug**

If you reference a resource that was created with the `&{}` [syntax](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-foreach-example-resource.html#intrinsic-function-reference-foreach-example-non-alphanumeric), the stack will fail with unresolved resource dependencies template format error:

```
Template format error: Unresolved resource dependencies [SNS&{TopicId}] in the Resources block of the template
```

### **Expected behavior**

ForEach transform resolves the generated resource.

### **Observed behavior**

ForEach transform does not resolve the referenced generated resource.

### **Test cases**

```
Transform: 'AWS::LanguageExtensions'
Parameters:
  TopicIds:
    Type: CommaDelimitedList
    Default: us.anthropic.claude-3-5-sonnet-20241022-v2:0
Resources:
  'Fn::ForEach::Topics':
    - TopicId
    - !Ref TopicIds
    - 'SNS&{TopicId}':
        Type: "AWS::SNS::Topic"

      'ALARM&{TopicId}':
        Type: AWS::CloudWatch::Alarm
        Properties:
          ActionsEnabled: true
          OKActions:
            - !Ref
              'Fn::Sub': "SNS&{TopicId}"
          AlarmActions: 
            - !Ref
                'Fn::Sub': "SNS&{TopicId}"
          InsufficientDataActions: []
          MetricName: ModelMetric
          Namespace: CustomNamespace
          Statistic: Sum
          Dimensions:
            - Name: TopicId
              Value: !Ref TopicId
          Period: 10
          EvaluationPeriods: 1
          DatapointsToAlarm: 1
          Threshold: 0  
          ComparisonOperator: GreaterThanOrEqualToThreshold
          TreatMissingData: notBreaching
```

### **Additional context**

Only workaround is not to use the `&{}` syntax and provide only alphanumeric identifiers:
```
Transform: 'AWS::LanguageExtensions'
Parameters:
  TopicIds:
    Type: CommaDelimitedList
    Default: usanthropicclaude353sonnet20241022v20
Resources:
  'Fn::ForEach::Topics':
    - TopicId
    - !Ref TopicIds
    - 'SNS${TopicId}':
        Type: "AWS::SNS::Topic"

      'ALARM${TopicId}':
        Type: AWS::CloudWatch::Alarm
        Properties:
          ActionsEnabled: true
          OKActions:
            - !Ref
              'Fn::Sub': "SNS${TopicId}"
          AlarmActions: 
            - !Ref
                'Fn::Sub': "SNS${TopicId}"
          InsufficientDataActions: []
          MetricName: ModelMetric
          Namespace: CustomNamespace
          Statistic: Sum
          Dimensions:
            - Name: TopicId
              Value: !Ref TopicId
          Period: 10
          EvaluationPeriods: 1
          DatapointsToAlarm: 1
          Threshold: 0  
          ComparisonOperator: GreaterThanOrEqualToThreshold
          TreatMissingData: notBreaching
```
