### ISSUE TITLE
fn::foreach to return array or alternative that provides the ability to construct dynamic array.

### ISSUE THREAD

**Issue by ashtonian** [aws-cloudformation/cfn-language-discussion#165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**

There is currently no way to construct a dynamically sized array as seen in the example below. Fn::ForEach fails here as it returns a map and not an array which is not applicable. I think there are many use cases, this is a very simple one when trying to create a load balancer target group. 

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'example'
Transform: 'AWS::LanguageExtensions'

Parameters:
  IPs:
    Description: Comma-separated list of private IP addresses.
    Type: CommaDelimitedList
Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: Name
      VpcId: vpc-12345678
      Protocol: TCP
      Port: 1234
      TargetType: ip
      HealthCheckProtocol: TCP
      Targets:
        'Fn::ForEach::TargetList':
          - EndpointIP
          - !Ref IPs
          - Id: !Ref EndpointIP
            Port: !Ref DBEndpointPort
```

There are no alternatives currently even if the number is fixed you have to do some cumbersome work with !Select to get it to work. 

```yaml
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: Name
      VpcId: vpc-12345678
      Protocol: TCP
      Port: 1234
      TargetType: ip
      HealthCheckProtocol: TCP
      Targets:
        - Id: !Select [0, !Ref IPs]
          Port: 1234
        - Id: !Select [1, !Ref IPs]
          Port: 1234
...
```
