### ISSUE TITLE
Way to check for index is out of bounds for !Select function

### ISSUE THREAD

**Issue by Trane9991** [aws-cloudformation/cfn-language-discussion#37]
`!Select` function [documentation](https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-select.html) mentions following:

> Fn::Select does not check for null values or if the index is out of bounds of the array. Both conditions will result in a stack error, so you should be certain that the index you choose is valid, and that the list contains non-null values.

Without the ability to check for the provided array length CloudFormation is impossible to implement some very simple solutions. 

For example, I need to create an [`AWS::EFS::MountTarget`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-mounttarget.html) for each user-provided subnet, but it is impossible because I can't know how many subnets user will provide.

For example:
```yml
Parameters:
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSVolume
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: !Select [0, !Ref Subnets] 
  EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSVolume
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: !Select [1, !Ref Subnets]
```

Will fail if the user will provide only one subnet.

Attempt to add the following condition:
```yml
Conditions:
   IsSubnet1: !Not [!Equals [!Select [ 0, !Ref Subnets], !Ref AWS::NoValue ]] 
   IsSubnet2: !Not [!Equals [!Select [ 1, !Ref Subnets], !Ref AWS::NoValue ]] 
```
Fails with the error: `ValidationError: Template error: every Fn::Equals object requires a list of 2 string parameters.`

Another attempt:
```yml
Conditions:
   IsSubnet1: !Not [!Equals [!Select [ 0, !Ref Subnets], "" ]] 
   IsSubnet2: !Not [!Equals [!Select [ 1, !Ref Subnets], "" ]] 
```
Fails with the error: `ValidationError: Template error: Fn::Select  cannot select nonexistent value at index 1`
