### ISSUE TITLE
Support YAML anchors/aliases in CFN yaml templates

### ISSUE THREAD

**Issue by x6j8x** [aws-cloudformation/cfn-language-discussion#49]

**Comment by Lucas3oo** [comment]
+1

**Comment by manchicken** [comment]
+1

**Comment by davidjb** [comment]
Having equivalent support within [AWS Step Function state machine definitions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-statemachine-s3location.html) as well would be great help to reduce and centralise repetitive configuration. In the config I've tried to deploy just now, using an alias results in `SCHEMA_VALIDATION_FAILED` (`InvalidDefinition`) errors; anchors seem okay to remain in the YAML but serve no purpose without aliases to reference them.

**Comment by yvele** [comment]
> Maybe a useful note for someone: when using `aws cloudformation package` via AWS CLI, it processes the YAML and anchors works just fine.

@krystof-k  you mean that we have to use [`aws cloudformation package`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/package.html) with `--use-json` option:

```sh
aws cloudformation package \
  --template template.yaml \
  --s3-bucket somebucketforcloudformation \
  --output-template-file template.json \
  --use-json
```

When converting from YAML to JSON, all anchors and aliases will be resolved.

More info on this workaround: https://medium.com/@rhgvandenheuvel/cloudformation-coding-using-yaml-9127025813bb

But I would prefer this being natively handled by CloudFormation as YAML is more readable than JSON.

**Comment by krystof-k** [comment]
@yvele Yes, but you don't have to convert it JSON, it works with YAML too:

```console
aws cloudformation package \
  --template-file template.yaml \
  --output-template-file packaged-template.yaml \
  --s3-bucket bucket
```

**Comment by yvele** [comment]
@krystof-k yeah you are right 👍 

I'm facing errors because I want to use anchors/aliases within a StackSet template body: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html#cfn-cloudformation-stackset-templatebody

```yaml
StackSet:
  Type: AWS::CloudFormation::StackSet
  Properties:
    TemplateBody: |
      Foo: &anchor
        - a
        - b
      Bar: *anchor
```

and obviously `TemplateBody` is a string and anchor/aliases will not be converted within 🤔 I'm a bit stuck

I tried the following:

```yaml
Transform: AWS::LanguageExtensions
...

StackSet:
  Type: AWS::CloudFormation::StackSet
  Properties:
    TemplateBody: !ToJsonString
      Foo: &anchor
        - a
        - b
      Bar: *anchor
```

It's kind of working.. but the problem with `ToJsonString` is that my object will have `GetAtt`, etc. being resolved outside the StackSet (resolved from the root document):

```yaml
Transform: AWS::LanguageExtensions
...

StackSet:
  Type: AWS::CloudFormation::StackSet
  Properties:
    TemplateBody: !ToJsonString
      SomeResource:
        Type: AWS::SomeResource
      Foo: $anchor
        - a
        - !GetAtt SomeResource.Arn # This will try to find SomeResource in the root document outside the StackSet
      Bar: *anchor
```

> Template error: instance of Fn::GetAtt references undefined resource SomeResource


I can't find any workaround to resolve anchors/aliases within a StackSet 🤔
