### ISSUE TITLE
Template Variables

### ISSUE THREAD

**Issue by rhboyd** [aws-cloudformation/cfn-language-discussion#55]

**Comment by bjorg** [comment]
This is hugely beneficial. Big +1! When can we get this?

The `Value` key should support 3 types of notation: string, list, and map. Also, `Type` should be optional.

```yaml
Variables:
  MyTextVariable:
    Value: !Sub "${STAGE}.${DOMAIN}"
  MyListVariable:
    Value:
      - First Value
      - Second Value
  MyMapValue:
    Value:
      First: Value
      Second: Other Value
```

**Comment by benkehoe** [comment]
I'd say that the value should be able to be *any* valid JSON type, and that putting, say, `Type: Number` on it should allow for conversion of a string containing a number into a proper number.

I also think there's a good argument that the type should also be able to be any CloudFormation resource type, where the value is a valid identifier for that type, and the resulting variable (after a call to the type's read handler) can be `Ref`'d and `GetAtt`'d like a resource. (I think this should be true for template parameters as well).

**Comment by bjorg** [comment]
As far as I can tell, the only literal type in CloudFormation is `string`. The various parameter types, such as `Number` are just input validators (as well as transforms, but that's out-of-scope anyway). These would not be appropriate for variables. For example, it wouldn't make sense to validate that a resource attribute is a number no larger than 10. How would such an assertion even work in practice?

## Ref
Implementing `Ref` is pretty simple as it only requires in-lining with infinite recursion detection. It also needs support for `Sub`.

_BEFORE:_
```yaml
Variables:
   MyMessage: !Sub "Hello ${Who}"
   Who: World
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref MyMessage
```

_AFTER:_
```yaml
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub 
        - "Hello ${Who}"
        - Who: World
```

## GetAtt

`GetAtt` is tricky, because it's only valid on resources. I'm not even sure how you would declare such a variable? You can't use `Ref` in the declaration since that has its own meaning.

Example, how would you declare that `MyTopicResource` is the actual resource and not its ARN (as returned by `Ref`)?
```yaml
Variables:
  MyTopicResource: !Ref MyTopic
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
```
