### ISSUE TITLE
Organizations pseudo parameters

### ISSUE THREAD

**Issue by rjpereira** [aws-cloudformation/cfn-language-discussion#57]

**Comment by PatMyron** [comment]
[OrganizationalUnit](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/642) too

**Comment by rajesh-bachu** [comment]
This would be also helpful to get org id reference when creating IAM or any resource policies to grant access from OrganizationID

**Comment by islamgohar** [comment]
that could help

**Comment by arielbeckjit** [comment]
> As a workaround, I created a stackset that creates an SSM parameter with the value of the OrganizationID and in that same stack instance I have an Output with an export of the OrgID so that other templates can just perform a resolve or !ImportValue

How did you do it? how did you extract the orgID and have set it into an output? using a lambda?

**Comment by husseinkohy** [comment]
if you are using in a resource policy couldn't you do it like:
`Condition:
                  StringEquals:
                  aws:PrincipalOrgID: "${aws:PrincipalOrgID}"`
based on documentation here: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html

**Comment by lowkasen** [comment]
This would really help with Control Tower deployments

**Comment by reidca** [comment]
I think this would be extremely helpful in creating platform stacksets. The number of times I have had to add the org id as a parameter is crazy. I cannot believe it is that hard to do. In general we need more pseudo parameters but I am hugely in favour of both the organization id and the organization unit id being added.

**Comment by gswallow** [comment]
> if you are using in a resource policy couldn't you do it like: `Condition: StringEquals: aws:PrincipalOrgID: "${aws:PrincipalOrgID}"` based on documentation here: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html

Great idea.  I doubt it's helpful for many of the use cases brought up in this issue, but I'm testing it with resource policies right now.

**Comment by Jacco** [comment]
Just found an elegant way to emit a ssm parameter (only works on the root account though).

No you'd need ssm parameter replication to other regions / accounts.

```yaml
Resources:
  OrganizationsResourcePolicy:
    Type: AWS::Organizations::ResourcePolicy
    Properties:
      Content:
          Version: 2012-10-17
          Statement:
            - Sid: AllowReadonlyNavigateOrganization
              Effect: Allow
              Principal:
                AWS: '*'
              Action:
                - organizations:ListRoots
                - organizations:ListOrganizationalUnitsForParent
                - organizations:ListAccountsForParent
              Resource: '*'
              Condition:
                StringEquals:
                  aws:PrincipalOrgID": "${aws:PrincipalOrgID}"
  OrganizationParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /organizations/id
      Value: !Select
        - 1
        - !Split 
          - /
          - !GetAtt OrganizationsResourcePolicy.Arn
      Type: String
```

Update:
Downside form the code above is that you have to create a `AWS::Organizations::ResourcePolicy` for it to work. And also that the parameter is not available cross account or cross region.

An easier approach is to create a stack with `AWS::Organizations::Organization`. This is nice because is has attributes you can use. You probably have to create the stack without the `AWS::CloudFormation::StackSet` first and import any existing `AWS::Organizations::Organization`. The stackset is than created and stackinstances created in all the accounts of the organisation (apart from the management account) and in al the regions of the input parameter.

```yaml
Parameters:
  Regions:
    Type: CommaDelimitedList
    Default: us-east-1,eu-central-1,eu-west-1,eu-west-2,eu-west-3
Resources:
  Organization:
    DeletionPolicy: Retain
    Type: AWS::Organizations::Organization
    Properties:
      FeatureSet: ALL
  ParameterStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: OrganizationParameterStack
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: True
        RetainStacksOnAccountRemoval: True
      ManagedExecution:
        Active: true
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: 
              - !GetAtt Organization.RootId
          Regions: !Ref Regions
      TemplateBody: !Sub
        - |
          {
            "AWSTemplateFormatVersion": "2010-09-09",
            "Resources": {
              "AtLeastOneResource": {
                "Type": "AWS::CloudFormation::WaitConditionHandle"
              }
            },
            "Outputs": {
              "OrganizationId": {
                "Description": "Id of the Organization",
                "Value": "${OrganizationId}",
                "Export": {
                  "Name": "organizationId"
                }
              }
            }
          }
        - OrganizationId: !GetAtt Organization.Id
```
